pages:
  stage: deploy
  image: python:3.12-alpine
  before_script:
    - pip install "mkdocs-material==9.7.7" "mkdocs-rss-plugin==1.19.0"
  script:
    - mkdocs build --strict
    - mv site public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
