pages:
  stage: deploy
  image: python:3.12-alpine
  before_script:
    - pip install mkdocs mkdocs-simple-blog pymdown-extensions
  script:
    - mkdocs build --strict
    - mv site public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH