pages:
  stage: deploy
  image: hugomods/hugo:debian-ci-0.165.0
  before_script:
    - curl -sL -o /tmp/pagefind.tar.gz https://github.com/CloudCannon/pagefind/releases/download/v1.5.2/pagefind-v1.5.2-x86_64-unknown-linux-musl.tar.gz
    - tar -xzf /tmp/pagefind.tar.gz -C /usr/local/bin pagefind
  script:
    - hugo --minify
    - pagefind --site public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
